# The MIT License (MIT)
#
# Copyright (c) 2016 Sean Quinn
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

version: '2'

services:

  proxy:
    build: ./proxy
    image: https-subdomains/acme
    container_name: https_subdomains_acme_proxy
    hostname: acme.com
    ports:
      - '80:80'
      - '443:443'
    links:
      - acme_app_server:nginx_acme_app
      - acme_www_server:nginx_acme_www

  acme_app_server:
    build: ./nginx
    image: https-subdomains/acme-app-server
    container_name: https_subdomains_acme_app_server
    hostname: app.acme.com
    ports:
      - '8079:8079'
    volumes_from:
      - acme_app_data:ro

  acme_www_server:
    build: ./nginx
    image: https-subdomains/acme-www-server
    container_name: https_subdomains_acme_www_server
    hostname: www.acme.com
    ports:
      - '8080:8080'
    volumes_from:
      - acme_www_data:ro

  acme_app_data:
    build: ./acme.com-app
    image: https-subdomains/acme-app-data
    container_name: https_subdomains_acme_app_data

  acme_www_data:
    build: ./acme.com-www
    image: https-subdomains/acme-www-data
    container_name: https_subdomains_acme_www_data
